### ISSUE TITLE
Deprecate get_entity and get_weights

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-survey-manager#128]
I found these two helps around these [line](https://github.com/openfisca/openfisca-survey-manager/blob/master/openfisca_survey_manager/scenarios.py#L1235).
Since there are not used anywhere I wonder if they should be removed.

They are not used in openfisca-france-data nor openfisca-senegal etc

@claireleroy : do we use them in taxipp ?

**Comment by claireleroy** [comment]
No, only in old versions

**Comment by benjello** [comment]
Ok. So we need to remove them.
