### ISSUE TITLE
SAS7BDAT in requirement

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-survey-manager#13]
There is some import that needs sas7bdat package. Should we put that as a requirement in setup.py ?

**Comment by benjello** [comment]
It is not mandatory (you can have only stata files) but yes we should include it as part of the sas option

**Comment by adrienpacifico** [comment]
You think we should do it with [extras](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) ?

Then do a :
`pip install openfisca-survey-manager[SAS]` ?

This might expend the issue but as far as I can see if we want to be complete in the [setup.py](https://github.com/openfisca/openfisca-survey-manager/blob/master/setup.py) :

 Table type | Needed package(s)| Done | size 
-------|-------- | --- | ---
 SAS | SAS7BDAT |  |<1MB
SPSS | savReaderWriter| |  48MB
DBF | Pysal |  |15MB
Stata | pandas | x | 15MB
CSV | pandas | x | 15MB


Since SAS7BDAT is fairly small, we might want to install it by default, and provide options for more demanding packages in term of size, namely DBF and SPSS ?

**Comment by benjello** [comment]
Yes a in [here](https://github.com/openfisca/openfisca-france/blob/master/setup.py)
pandas has a read_sas command now. It uses SAS7BDAT and I do not know if it requires SAS7BDAT or has just  copied it. That should be checked.

**Comment by benjello** [comment]
You are right about the other formats: there should be optionnal
