### ISSUE TITLE
clean_data_frame should better handle integers

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-survey-manager#17]
For strings converted to integers and original integers, the programme should try to convert them to
low memory integers like int16, int32 etc.

**Comment by adrienpacifico** [comment]
Partage d'une erreur que j'ai fait à ce sujet, si on demande un int16 alors que le nombre est plus grand ou plus petit que 32,768 , le programme tourne quand même, mais fourni des valeurs aberrantes (et j'ai mis du temps à trouver l'erreur :p ).

Un `try :  except :` fonctionnera toujours il me semble, donc faire attention que le type est dans l'intervalle de la valeur.

```
a = pd.Series([10**5])
a.astype('int16')
print a
# -31072
```

**Comment by benjello** [comment]
J'ai également eu ce genre de problème mais ils sont venus lors du calcul d'agrégats.
C'est pour cela qu'il faut essayer de convertir à ce moment là en float64.
On pourrait également faire des checks sur certaines variables.

**Comment by adrienpacifico** [comment]
```python
a = pd.Series([32000]) ; b = pd.Series([32000])
a = a.astype('int16') ; b = b.astype('int16')
a+b
# 0   -1536
#dtype: int16
````
Fou que pandas 0.19 fasse ça sans warning, du coup je comprends pour les agrégats.

Du coup il faut être précautionneux. Est-tu sûr que le jeux en vaut la chandelle niveau performance ?

**Comment by benjello** [comment]
Je trouve normal que pandas ne fasse pas de warning: le fait de passer en int16 permet de gagner de la mémoire et de faire les calculs d'une certaine façon. S'il doit les faire en int16 et int64 et comparer à chaque fois, il est pas rendu. Par défaut, il fait tout en int64 mais si l'utilsiateur force le int16, il le fait à ses risques et périls.
Pour la mémoire je pense que cela vaut le coup si on a de grandes bases.

**Comment by adrienpacifico** [comment]
ok, que penses tu de prendre de la marge ? S'assurer par exemple que le type corresponde à au moins 60 fois la taille de base de la variable (ou autre). Exemple, je somme le salaire de chaque mois sur 18 mois pour 3 personnes dans le foyer on est à 54 fois la variable de base.
Et mettre un warning dans la doc, faut que les utilisateurs soient au courant du péril :-).

Ce que j'observe c'est en gros une diminution par deux de la taille de mes array pour du passage d'un `float64`à un `float32`, pareil de 32 à 16, etc.

Quid de la compression des HDF par rapport à de la réduction de typage ?

Tu penses à quoi comme grandes bases ?

**Comment by benjello** [comment]
Le passage du codage à 64 bits à 32 bits réduisent par 2, cela découle de la définition.
Pour les variables type salaires etc, il faut peut-être les garder en float64 même si avec du float32 on a de la marge 
```
info(np.float32).max = 3.4028234663852886e+38
info(np.float16).max =  65504.0
```
Le HDF c'est pour le stockage, quand les données viennent en RAM, il faut tout de façon de la place.
Des bases de caisse de retraite, des bases fiscales type échantillon lourd etc

**Comment by adrienpacifico** [comment]
> Le passage du codage à 64 bits à 32 bits réduisent par 2, cela découle de la définition.
Ok, effectivement y'a 2 fois plus de bits...

Effectivement, je crois que le 32 bit suffira pour tout les usages. 

Pour les grosses bases, peut être qu'il faudrait plus passer par du [querying](http://pandas.pydata.org/pandas-docs/stable/io.html#querying) dans les manipulations de données (of-france-data) pour éviter de trop consommer de mémoire ?

**Comment by benjello** [comment]
Oui pour la préparation des données mais il y aura toujours le problème du run de openfisca
