### ISSUE TITLE
Fix deploying stage

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-survey-manager#22]
The deploy stage [doesn't work](https://travis-ci.org/openfisca/openfisca-survey-manager#L238).
I need you here @fpagnoux ;-)

**Comment by benjello** [comment]
New [failing test](https://travis-ci.org/openfisca/openfisca-survey-manager/builds/179563760) after adding a missing file.

**Comment by fpagnoux** [comment]
I had written some doc about it, but forgot to publish it...
It's now [here](https://doc.openfisca.fr/en/contribute/release-process.html#set-up-automated-releasing-on-a-new-repository).

What you're missing is an ssh key to be allowed to publish a tag in your repository. It is documented in the link above, put please tell me what's unclear so that I can improve it !

**Comment by benjello** [comment]
travis login
We need your GitHub login to identify you.
This information will not be sent to Travis CI, only to api.github.com.
The password will not be displayed.

Try running with --github-token or --auto if you don't want to enter your password anyway.

Username: benjello
Password for benjello: ********
Two-factor authentication code for benjello: 756175
Successfully logged in as benjello!
GH request failed
verb:               :delete
url:                /authorizations/68703678
headers:            {"User-Agent"=>"GH/0.15.0", "Accept"=>"application/vnd.github.v3+json", "Accept-Charset"=>"utf-8", "X-GitHub-OTP"=>"756175"}
error:              Faraday::ClientError: the server responded with status 401
payload:            nil
response_status:    401
response_headers:   {"server"=>"GitHub.com", "date"=>"Tue, 29 Nov 2016 11:01:53 GMT", "content-type"=>"application/json; charset=utf-8", "content-length"=>"160", "connection"=>"close", "status"=>"401 Unauthorized", "x-github-otp"=>"required; sms", "x-github-media-type"=>"github.v3; format=json", "x-ratelimit-limit"=>"60", "x-ratelimit-remaining"=>"58", "x-ratelimit-reset"=>"1480420898", "access-control-expose-headers"=>"ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval", "access-control-allow-origin"=>"*", "content-security-policy"=>"default-src 'none'", "strict-transport-security"=>"max-age=31536000; includeSubdomains; preload", "x-content-type-options"=>"nosniff", "x-frame-options"=>"deny", "x-xss-protection"=>"1; mode=block", "x-github-request-id"=>"500FD5F2:5893:130C9322:583D6021"}
response_body:      {"message":"Must specify two-factor authentication OTP code.","documentation_url":"https://developer.github.com/v3/auth#working-with-two-factor-authentication"}
for a full error report, run travis report
benjello@WKS-IPP-6:~/openfisca/openfisca-survey-manager(migration-corev4 *$>)$ travis report
System
Ruby:                     Ruby 2.3.1-p112
Operating System:         Debian testing
RubyGems:                 RubyGems 2.5.1

CLI
Version:                  1.8.4
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2016-11-29 12:02:45 +0100

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)

Last Exception
An error occurred running `travis login`:
    GH::Error: GH request failed
verb:               :delete
url:                /authorizations/68703678
headers:            {"User-Agent"=>"GH/0.15.0", "Accept"=>"application/vnd.github.v3+json", "Accept-Charset"=>"utf-8", "X-GitHub-OTP"=>"756175"}
error:              Faraday::ClientError: the server responded with status 401
payload:            nil
response_status:    401
response_headers:   {"server"=>"GitHub.com", "date"=>"Tue, 29 Nov 2016 11:01:53 GMT", "content-type"=>"application/json; charset=utf-8", "content-length"=>"160", "connection"=>"close", "status"=>"401 Unauthorized", "x-github-otp"=>"required; sms", "x-github-media-type"=>"github.v3; format=json", "x-ratelimit-limit"=>"60", "x-ratelimit-remaining"=>"58", "x-ratelimit-reset"=>"1480420898", "access-control-expose-headers"=>"ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval", "access-control-allow-origin"=>"*", "content-security-policy"=>"default-src 'none'", "strict-transport-security"=>"max-age=31536000; includeSubdomains; preload", "x-content-type-options"=>"nosniff", "x-frame-options"=>"deny", "x-xss-protection"=>"1; mode=block", "x-github-request-id"=>"500FD5F2:5893:130C9322:583D6021"}
response_body:      {"message":"Must specify two-factor authentication OTP code.","documentation_url":"https://developer.github.com/v3/auth#working-with-two-factor-authentication"}
        from /var/lib/gems/2.3.0/gems/faraday-0.10.0/lib/faraday/response/raise_error.rb:13:in `on_complete'
        from /var/lib/gems/2.3.0/gems/faraday-0.10.0/lib/faraday/response.rb:9:in `block in call'
        from /var/lib/gems/2.3.0/gems/faraday-0.10.0/lib/faraday/response.rb:61:in `on_complete'
        from /var/lib/gems/2.3.0/gems/faraday-0.10.0/lib/faraday/response.rb:8:in `call'
        from /var/lib/gems/2.3.0/gems/faraday-0.10.0/lib/faraday/request/retry.rb:116:in `call'
        from /var/lib/gems/2.3.0/gems/faraday-0.10.0/lib/faraday/request/authorization.rb:38:in `call'
        from /var/lib/gems/2.3.0/gems/faraday-0.10.0/lib/faraday/rack_builder.rb:139:in `build_response'
        from /var/lib/gems/2.3.0/gems/faraday-0.10.0/lib/faraday/connection.rb:377:in `run_request'
        from /var/lib/gems/2.3.0/gems/gh-0.15.0/lib/gh/remote.rb:77:in `http'
        from /var/lib/gems/2.3.0/gems/gh-0.15.0/lib/gh/token_check.rb:28:in `http'
        from /var/lib/gems/2.3.0/gems/gh-0.15.0/lib/gh/instrumentation.rb:16:in `block in http'
        from /var/lib/gems/2.3.0/gems/gh-0.15.0/lib/gh/instrumentation.rb:30:in `instrument'
        from /var/lib/gems/2.3.0/gems/gh-0.15.0/lib/gh/instrumentation.rb:16:in `http'
        from /var/lib/gems/2.3.0/gems/gh-0.15.0/lib/gh/remote.rb:84:in `request'
        from /var/lib/gems/2.3.0/gems/gh-0.15.0/lib/gh/remote.rb:100:in `delete'
        from /var/lib/gems/2.3.0/gems/travis-1.8.4/lib/travis/tools/github.rb:223:in `block (2 levels) in login'
        from /var/lib/gems/2.3.0/gems/travis-1.8.4/lib/travis/tools/github.rb:52:in `ensure in each_token'
        from /var/lib/gems/2.3.0/gems/travis-1.8.4/lib/travis/tools/github.rb:52:in `each_token'
        from /var/lib/gems/2.3.0/gems/travis-1.8.4/lib/travis/tools/github.rb:36:in `with_token'
        from /var/lib/gems/2.3.0/gems/travis-1.8.4/lib/travis/cli/login.rb:31:in `login'
        from /var/lib/gems/2.3.0/gems/travis-1.8.4/lib/travis/cli/login.rb:40:in `run'
        from /var/lib/gems/2.3.0/gems/travis-1.8.4/lib/travis/cli/command.rb:198:in `execute'
        from /var/lib/gems/2.3.0/gems/travis-1.8.4/lib/travis/cli.rb:64:in `run'
        from /var/lib/gems/2.3.0/gems/travis-1.8.4/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
benjello@WKS-IPP-6:~/openfisca/openfisca-survey-manager(migration-corev4 *$>)$ travis login
We need your GitHub login to identify you.
This information will not be sent to Travis CI, only to api.github.com.
The password will not be displayed.

Try running with --github-token or --auto if you don't want to enter your password anyway.

Username: benjello 
Password for benjello: ********
Two-factor authentication code for benjello: 825918
Validation Failed
for a full error report, run travis report

**Comment by benjello** [comment]
Fixed
