### ISSUE TITLE
Pakcaging: user defined paths and access to scripts

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-survey-manager#24]
To finish packaging this repo, a few features are needed:
 - [x] Store the config `.ini` file in the user config directory
 - [x] Make the [`build_collection`](https://github.com/openfisca/openfisca-survey-manager/blob/master/openfisca_survey_manager/scripts/build_collection.py) script available in userland.

@fpagnoux @cbenz @MattiSG suggestions on how to proceed needed here ;-)

**Comment by fpagnoux** [comment]
> Make the build_collection script available in userland.

You should check [this](https://github.com/openfisca/openfisca-web-api/blob/master/setup.py#L41).
It creates a terminal shortcut.

> Store the config .ini file in the user config directory

@cbenz probably knows better than me, I've never done it.

**Comment by benjello** [comment]
Thanks @fpagnoux !

**Comment by benjello** [comment]
@cbenz : je crois que j'ai retrouvé le nom du paquet dont tu m'avais parlé, mais en fait il y en a 2:
 - [pyxdg](https://pypi.python.org/pypi/pyxdg)
 - [xdg](https://pypi.python.org/pypi/xdg)

Lequel dois-je utiliser ? Par avance merci !

**Comment by benjello** [comment]
Done
