### ISSUE TITLE
package not working in the CASD

### ISSUE THREAD

**Issue by clallemand** [openfisca/openfisca-survey-manager#278]
Hi there!

I really enjoy OpenFisca-Survey-Manager, but I recently encountered an issue.

### Here is what I did:

I try to use openfisca-survey-manager in the CASD

### Here is what I expected to happen:

To be able to use openfisca-survey-manager as a conda package in the CASD

### Here is what actually happened:

I can't because in the __init__ file of openfisca-survey-manager a file `config.ini` as to be written in the package location (for the tests, line 48 of `openfisca_survey_manager/__init__`.

However in the CASD I don't have the permission to write in the package location. 

## Context

I identify more as a:

- Economist _(I make microsimulations with real populations)_.
- Developer _(I create tools that use OpenFisca-Survey-Manager)_.
- Commenter _(I make data visualisations)_.
- LexImpact _(I model reforms to make them exist)_.

cc @benjello

**Comment by benjello** [comment]
I think we should restrict the stuff with the `test_config_files` only to CIs or to user install.
May be a simple try/except wil do the job.

**Comment by clallemand** [comment]
@benjello j'ai tenté une correction [ici](https://github.com/openfisca/openfisca-survey-manager/pull/280). Est ce que ça te semble convenir ?
