### ISSUE TITLE
Generate an error in compute_aggregate when no weight variable (because weighted = True by default)

### ISSUE THREAD

**Issue by bfabre01** [openfisca/openfisca-survey-manager#287]
Currently, in `compute_aggregate`, `weighted = True` by default but, when the variable for which one wants to compute an aggregate has no assigned weight variable, there is only a warning, and the aggregate is computed with uniform weights. This is an important source of error.
This may imply to adjust some tests. For example, `test_compute_aggregate` calls a `compute_aggregate` with `weighted = True` (the default), but with no assigned weight.

We realized this error by doing the PR #286 , where we wanted to have attributes of the weight variable (e.g. `is_period_size_independent`), but the above test did not work anymore, because no attribute for a None variable.

Check whether this problem exists for other methods.

**Comment by benjello** [comment]
@bfabre01 : is this solved ? If yes, please close the issue.
Otherwise could you write down a minimal example where this error occurs ?
Or would you just have an error in place of the warning ?

**Comment by bfabre01** [comment]
PR associée est mergée. Je ferme.
