### ISSUE TITLE
check-version-and-changelog stop working properly

### ISSUE THREAD

**Issue by benoit-cty** [openfisca/openfisca-survey-manager#288]
### Here is what I did:

Add functionnal changes to OpenFisca

### Here is what I expected to happen:

Merge is blocked until I update version number.

### Here is what actually happened:

check-version-and-changelog.sh return an error, indicating that there is no need for version bump. But the error is in the case that is not supposed to throw an error.
[check-version-and-changelog](https://github.com/openfisca/openfisca-survey-manager/actions/runs/7665948427/job/20892845216#logs)

## Context

I identify more as a Developer _(I create tools that use OpenFisca-Survey-Manager)_.

**Comment by benjello** [comment]
@benoit-cty could we close this issue ?

**Comment by benoit-cty** [comment]
Oh yes, it is merged.
