### ISSUE TITLE
Trigger testing everytime openfisca-core master branch is modified

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-survey-manager#55]
As a user of core I do need to anticipate what can be broken in a generic package like openfisca-survey-manager.

I thus want to trigger testing with the last version of openfisca-core to detect breaking changes early enough to fix them as ASAP.

**Comment by sandcha** [comment]
On travis, I don't know.
If you move to circleci we could define a step that checks openfisca-core updates and `on_success`, execute steps of install with latest core/country revisions and launch tests (cf. example in [cicleci documentation on when attribute](https://circleci.com/docs/2.0/configuration-reference/#the-when-attribute)).

**Comment by benjello** [comment]
#54 does the job !
